### PR TITLE
Modifications by inuyaksa

### PR DESCRIPTION
**Pull request by legoboyvdlp**
### Checklist:

* [ ] My changes follow the Contributing Guidelines. 
* [ ] My changes implement realistic features. 
* [ ] Please have a main Developer test my changes before merging. 
* [x] My changes are ready for merging.

### CODE REVIEW

**Comment by merspieler** [comment]
What has been changed?

On a quick glance at the code, I've spotted a few white spaces at the line endings...

**Comment by legoboyvdlp** [comment]
Look at the diff.

**Comment by legoboyvdlp** [comment]
I already removed some of those whitespaces btw.

**Comment by inuyaksa** [comment]
> 
> 
> What has been changed?
> 
> On a quick glance at the code, I've spotted a few white spaces at the line endings...

I've add flight log and sensors pages with OOOI phase processor.
Change last-page prop logic on MCDU.

Sorry for the whitespaces.

**Pull request merged**
