### PR TITLE
Add weather effects on windshield

### PR DESCRIPTION
**Pull request by colingeniet**
### Description of  Changes
Adds rain/frost effects (cf. issue #85).
To do:
* [x] Enable weather effects - the code existed but did not work because of a typo.
* [x] Rework/simplify icing system code
* [x] Improve rain splashes animation. At low speed they seem to bounce around as the wind varies.
* [ ] ~~Add wipers~~ For later, depends on new 3D model.

Do you have any recommendation, request, or comment on this?

The typo I am talking about is `s/Windsheild/Windshield/` in the 3 `fuselage.ac` files.
If anyone is working with some source files for these models, they likely have the same typo.
It would be nice of them to fix it in the source so that it does not come back.

### Checklist:
* [x] My changes follow the Contributing Guidelines. 
* [x] My changes implement realistic features. 
* [ ] Please have a main Developer test my changes before merging. 
* [x] My changes are ready for merging.

### CODE REVIEW

**Comment by legoboyvdlp** [comment]
Sorry, please don't touch the exterior 3D model

Could you fix the effect file instead?

I'll notify captB as well.

>  Add wipers. This will require some 3D model work, if I understood correctly there is some work in progress on the models, so maybe keep that for later?

This is already in the new model.

**Comment by colingeniet** [comment]
No problem, I changed the `fuselage.xml` file instead.
Force pushed (sorry) to keep the `fuselage.ac` history clean.

**Review by legoboyvdlp — APPROVED** [review]
Excellent changes, thank you!

**Comment by legoboyvdlp** [comment]
Is this ready to merge or not?

**Comment by colingeniet** [comment]
No sorry, I still want to rework `Systems/glass-effect.xml`

**Comment by colingeniet** [comment]
Ready for merge, can you please review the latest changes?

I am still not quite happy with the way rain drops move when accelerating, but I think my issue is more with the shader itself.

**Comment by merspieler** [comment]
It's not ready for mergre!!!
```
   29.98 [ALRT]:nasal      Nasal runtime error: Timer is running, cannot change type between real/sim time
   29.98 [ALRT]:nasal        at /games/.fgfs/Aircraft/A320-family/Nasal/Systems/icing.nas, line 145
   29.98 [ALRT]:nasal        called from: /games/.fgfs/Aircraft/A320-family/Nasal/Sim/libraries.nas, line 214
   29.98 [ALRT]:nasal        called from: /games/.fgfs/Aircraft/A320-family/AircraftConfig/acconfig.nas, line 423
   29.98 [ALRT]:nasal        called from: /games/.fgfs/Aircraft/A320-family/AircraftConfig/acconfig.nas, line 517
   29.98 [ALRT]:nasal        called from: , line 1
```
When using autostart to state ready for take off

**Comment by colingeniet** [comment]
Indeed, I did not realize that the `init` functions were called several times in that case, mea culpa.
Thank you for testing it.

**Comment by merspieler** [comment]
Thanks

**Pull request merged**
