### PR TITLE
FMGC fixed typo

### PR DESCRIPTION
**Pull request by kchodl**
Fixed typo in FMGC.nas

### Description of Changes
Corrected variable name

### Bugs fixed (if any)
Mismatch: ktToMach vs. ktsToMach

### Checklist:

* [x ] My changes follow the Contributing Guidelines. 
* [ ] My changes implement realistic features. 
* [ ] Please have a main Developer test my changes before merging. 

I apologize for any inaccuracies in this description.

### CODE REVIEW

**Review by Octal450 — CHANGES_REQUESTED** [review]
This is insufficient. You need to replace "all" instances of those variables names.

**Comment by vezza** [comment]
Hi!, it seems to me that all the instances of those variables have been replaced

**Comment by Octal450** [comment]
No, it isn't according to [72e6374](https://github.com/legoboyvdlp/A320-family/pull/344/commits/72e6374089e4bd0d8e8b63555b84f1ba91542ec0)

**Comment by Octal450** [comment]
Oh I see. My bad.

**Comment by Octal450** [comment]
I'm going to rename it kts to match the rest of the plane.

**Comment by Octal450** [comment]
61d009e

**Pull request closed without merging**
