### PR TITLE
New announcements and an Alitalia livery for A320 neo

### PR DESCRIPTION
**Pull request by MiSKLaCH**
### Description of Changes
- Changed the original announcements and added some new.
- Added the Alitalia EI-MSK livery for the A320 neo.

### Screenshots (optional)
ei-msk_scr1
ei-msk_scr2
ei-msk_scr3

### Checklist:
* [x] My changes follow the Contributing Guidelines. 
* [ ] My changes implement realistic features. 
* [ ] Please have a main Developer test my changes before merging. 
* [x] My changes are ready for merging.

### CODE REVIEW

**Comment by legoboyvdlp** [comment]
Hi,
The livery is nice but we can't take any new liveries right now. Happy to merge the announcements manually if you can confirm the source of them? Thanks!

**Comment by merspieler** [comment]
> The livery is nice but we can't take any new liveries right now. 

This is because of the new model.

Once that's in dev, feel free to rework and resubmit your work.

**Comment by legoboyvdlp** [comment]
Oh, nice catch on the seatbelt sound. I'm not sure about the smoking sign sound. It's not clear what that one is, since it obviously isn't used very much... but isn't it the same sound as the seatbelt? Certainly, when the gear is retracted, that's what is played. 

And of course, what is the source of these seatbelt sounds, to be sure? :)

**Comment by MiSKLaCH** [comment]
The announcements were taken from https://airodyssey.net/reference/inflight/ and tweaked a bit to my liking, then TTS'd via http://www.fromtexttospeech.com/ and filtered manually using Audacity. You can checkout all the announcements text and voices in the Announcements.txt in the root directory. Hope you like this very first pull request of mine, I wish I could help more on this fantastic project but I cannot code very well. I'm digging into it anyway ;)

Guys, thank you so much for this incredibly well made aircraft, it's really fun to fly and IMHO it's definetely the most realistic airliner in FGFS.

**Comment by MiSKLaCH** [comment]
> Oh, nice catch on the seatbelt sound. I'm not sure about the smoking sign sound. It's not clear what that one is, since it obviously isn't used very much... but isn't it the same sound as the seatbelt? Certainly, when the gear is retracted, that's what is played.
> 
> And of course, what is the source of these seatbelt sounds, to be sure? :)

I created those sounds a while ago for another project, I honestly don't remember how long it's been since then but they were made from scratch using Audacity and some filters.

If I remember well, I heard the smoking sound in a random YouTube video and to me it sounded like it was pitched up compared to the seatbelt one, but I may be wrong.

**Comment by legoboyvdlp** [comment]
Awesome, thanks. I'll add this shortly!

**Comment by legoboyvdlp** [comment]
Merged with a minor change at
https://github.com/legoboyvdlp/A320-family/pull/194

**Pull request closed without merging**
