### PR TITLE
Correct various labels on the flightdeck:

### PR DESCRIPTION
**Pull request by dg-505**
Here we go once again, sorry for the mess...

### Description of Changes

Right Flood light knob: From 'MAIN PNL' to 'PED'.

Weather Radar: From 'CCS' to 'GCS' (Ground Clutter Suppression).

EVAC switch: Add 'CAPT' label.

OH Fuel Panel: For left and right tank change pumps from 'L'/'R' to '1'/'2'.

Also OH Fuel Panel: On the A320ceo, the pumps are labeled 'PUMP 1' and 'PUMP 2' while the current labels 'L XFR'/'R XFR' belong to the A320neo. However the green lines showing the fuel pipes belong to the A320ceo (as well as the ECAM fuel page). Once the differences in the fuel systems are implemented (are they?), we should consider creating two variants of the labels and the ECAM page.

### Screenshots (optional)

fgfs-20240909140520

fgfs-20240909140552
fgfs-20240909140629
fgfs-20240909140655

### Checklist:

* [X] My changes follow the Contributing Guidelines. 
* [X] My changes implement realistic features. 
* [ ] Please have a main Developer test my changes before merging.

### CODE REVIEW

**Comment by Octal450** [comment]
The systems only model the ceo currently. Thx for this, will check in with Semir.

**Comment by L1011H** [comment]
Although the point mentioned are valid, I recommend not accepting this request.

Reason: Graphical changes MUST adhere to the workflow and be applied in the correct layer locally before being exported to the final texture, then commited and pushed. Otherwise, since this is not in sync locally with the source files, any changes merged will be reverted to the local version with the next commit from me.

Please consult me when planning any graphical change, the workflow on my side is done in such a way to minimize workload and potential problems and has to be adhered to.

**Comment by Octal450** [comment]
How do you suggest we proceed?

**Comment by L1011H** [comment]
> How do you suggest we proceed?

The listed issues were fixed as soon as I read and confirmed the them. They are ready locally and will be pushed as time permits. @dg-505 You will get credit for finding those when it's pushed, thank you. Please talk to us BEFORE attempting to do any graphics related work in the future as to save yourself the hassle.

**Comment by dg-505** [comment]
Thanks @L1011H, I didn't know that.

What do u think about having the source files (Gimp or Blender or whatever) in a "dev" subfolder or something similar? Or would that increase the risk that two or more people are working on the same source file and produce versioning conflicts?

**Comment by L1011H** [comment]
> Thanks @L1011H, I didn't know that.

This most likely should have been described somewhere CONTRIBUTING.md to make it clear.

> What do u think about having the source files (Gimp or Blender or whatever) in a "dev" subfolder or something similar? Or would that increase the risk that two or more people are working on the same source file and produce versioning conflicts?

This would be a total mess, version control systems are not really suited for graphics, especially something binary like the blender file format. For graphics work you need a tight group with very good communications and isolated tasks being assigned(example: one person makes the fuselage, the other the engines, the third & fourth divide  the textures into sub tasks between each other, etc) Ad hoc contributions usually do not work with graphics, especially if you are out of the loop.

**Comment by L1011H** [comment]
This has been pushed now. Thanks again for the report

**Comment by dg-505** [comment]
> This would be a total mess, version control systems are not really suited for graphics

Yes I understand that. I'll add a short notice to the Contributing.md

**Comment by dg-505** [comment]
See #337

**Pull request closed without merging**
