### PR TITLE
First stab at a remote MCDU via HTTP

### PR DESCRIPTION
**Pull request by niner**
As a cheap option for building a home cockpit, I implemented a remote MCDU as an HTML page that can be delivered via FlightGear's HTTP server (Phi).

### Description of Changes
The HTML page loads a screenshot of the captain's MCDU and updates it every second. All MCDU buttons are present as simple HTML table cells with click listeners that call the appropriate MCDU functions when fired. This way a touch screen (such as on a phone or tablet) can be used for easier input. The screenshot is additionally refreshed after each button press for less input lag. The layout is currently optimized for my phone's screen but should be easy to adapt via the body's font size setting. It can certainly benefit from some CSS wizard, but should be good enough for a first demonstration.

### Checklist:

* [X] My changes follow the Contributing Guidelines. 
* [X] My changes implement realistic features. 
* [ ] Please have a main Developer test my changes before merging. 
* [x] My changes are ready for merging.

### CODE REVIEW

**Comment by legoboyvdlp** [comment]
This looks interesting, nice!

**Comment by legoboyvdlp** [comment]
I'll test this later today

**Comment by legoboyvdlp** [comment]
When i press the buttons, I get this:


  333.96 [ALRT]:network    CanvasImage: task running, pausing for 15 seconds

along wtih a 15 second freeze.
Is it possible to avoid this?

**Comment by niner** [comment]
I just pushed a fix for this. If it doesn't completely fix it, there's also a 
workaround patch for FlightGear attached.

**Comment by legoboyvdlp** [comment]
If it needs changes to FlightGear I wouldn't be comfortable merging until you have these changes added upstream to FlightGear. It's reasonably easy, you can just write an email to the mailing list. However I will try this again, thank you!

**Comment by niner** [comment]
On Donnerstag, 11. März 2021 10:48:29 CET legoboyvdlp wrote:
> If it needs changes to FlightGear I wouldn't be comfortable merging until
> you have these changes added upstream to FlightGear. It's reasonably easy,
> you can just write an email to the mailing list. However I will try this
> again, thank you!

The patch for FlightGear should not be needed. With
https://github.com/legoboyvdlp/A320-family/pull/214/commits/
9f1bab9bb63a3270b4af256ea8930676bea856ce I don't get those messages anymore at 
all. But I have a pretty fast computer and that may be a factor so I posted 
the FlightGear patch just in case.

**Comment by legoboyvdlp** [comment]
Awesome, it works now, thank you!

**Pull request merged**
