### PR TITLE
Fixed Fire indications

### PR DESCRIPTION
**Pull request by merspieler**
Signed-off-by: merspieler <merspieler@airmail.cc>

### Description of Changes
Fixed the fire indications on the OVHD and pedestal (pending)

### Bugs fixed (if any)

#16 

### Checklist:

* [x] My changes follow the Contributing Guidelines. 
* [ ] My changes implement realistic features. 
* [ ] Please have a main Developer test my changes before merging. 
* [ ] My changes are ready for merging.

### CODE REVIEW

**Comment by merspieler** [comment]
@L1011H 
```
Fast-forward
 Models/FlightDeck/a320.flightdeck.xml          | 412 +++++++++++++++--------------
 Models/Instruments/OHpanel/OHpanel.xml         | 585 ++++++++++++++++++++++--------------------
 Models/Instruments/Pedestal_up/Pedestal_up.xml | 101 +++-----
 3 files changed, 553 insertions(+), 545 deletions(-)
```
You've got tonns of whitespace changes in there... please avoid that in future.

**Comment by legoboyvdlp** [comment]
I'm not so happy with this:

image

Is there anything else that could be done?

The pedestal looks great, and the code itself looks fine.

**Comment by L1011H** [comment]
> Is there anything else that could be done?
> 
> The pedestal looks great, and the code itself looks fine.

Fixed and pushed.

**Comment by merspieler** [comment]
I don't know, what you've changed but with the latest commits it doesn't work anymore for me...

**Comment by L1011H** [comment]
> I don't know, what you've changed but with the latest commits it doesn't work anymore for me...

It's not indicating fire or the button does not operate or both?

**Comment by legoboyvdlp** [comment]
It does light up; however, there seems to be some translation of the switch when it lights up, as well it doesn't light up very brightly, so at night its actually invisible!
fire-test

**Comment by L1011H** [comment]
Last reported issues should be fixed with latest commit. Please test when able @legoboyvdlp @merspieler

**Comment by legoboyvdlp** [comment]
Looks good now - thank you!

**Pull request merged**
