### PR TITLE
Altitude alert

### PR DESCRIPTION
**Pull request by legoboyvdlp**
@merspieler @hayden2000 

Would you mind checking this? I think I tested it fairly thoroughly, but please report any oddities.
Thanks!

### CODE REVIEW

**Comment by legoboyvdlp** [comment]
This is ready to merge as well.

**Comment by mattmaring** [comment]
Here are my observations:
1. DSC-31-40 P 25/32 seems to suggest that it should be ±200 ft instead of ±250 feet for the bounds
2. Amber should be flashing (yellow is pulse), so I think the timer on that needs to be faster (I would think 0.25 to match the other indicators on the pfd, but I have been unable to find a video on this so I'm not sure)
3. The logic on the 1.5s sound inhibit seems to be flipped, as the sound should play only when the autopilot is disengaged. Currently, it only plays when the autopilot is engaged.

**Comment by legoboyvdlp** [comment]
I'll check the 200 feet - I think that's a MSN difference as I've also seen 700 feet quoted elsewhere. Will see what other versions of the FCOM say :thinking: 

Regarding flashing, that's a good point, thanks, I suppose it should be more attention grabbing. Just wondering does flashing mean that it disappears completely or does it do the same as I have it now, but at a faster rate?

3. I'm not so sure about that as the logic schematic mentioned specifically one autopilot being engaged?

**Comment by legoboyvdlp** [comment]
The FCOM for the older aircraft that we have says 250 feet. So I presume it was changed 200 feet to comply with new regulations introduced by ICAO in '97 - so definitely going to change it!

**Comment by legoboyvdlp** [comment]
Found a source - so it disappears rather than pulsing by the looks of it.

https://www.youtube.com/watch?v=OrYqIU0NxHQ

**Comment by merspieler** [comment]
@legoboyvdlp at 0:38 it certainly starts flashing

**Comment by mattmaring** [comment]
For 3, in that video linked above, autopilot is disengaged and the c-chord plays. The current logic does the opposite.

**Comment by legoboyvdlp** [comment]
Surely at the end, about 1:35 the horn is sounding with AP2 (just) engaged?

**Comment by legoboyvdlp** [comment]
Ok - I've pushed a corrected version. I'll look into the autopilot issue in more depth, could be a MSN difference again.

**Review by mattmaring — APPROVED** [review]

**Comment by legoboyvdlp** [comment]
Ok - I figured it out - sorry, I missed that the schematic had a NOT logic gate on the autopilot. As I interpret the schematic, the leaving selected altitude alert may however sound when with autopilot engaged - the entire schematic is here if anyone wants to see - notice there is no condition on the autopilot except at the very top:

image

**Comment by legoboyvdlp** [comment]
If flying a non-precision approach you might well get activation of the horn - this matches what I saw in a video of a NPA to Insbruck. I will just verify one other thing...

**Pull request merged**
