### PR TITLE
Flightplan

### PR DESCRIPTION
**Pull request by legoboyvdlp**
Rework flightplan to use internal route manager. Allows access to new features and removes obsolete code

@octal450 @merspieler can you let me know of any issues please? Thanks 

Particularly keep an eye out for the /autopilot/route-manager/current-wp property ever going to -1. It shouldn't, I added code to prevent it, but it was a long-standing issue. Anything strange, let me know with steps to reproduce

### CODE REVIEW

**Comment by Octal450** [comment]
I can test this weekend.
Josh

**Comment by merspieler** [comment]
First quick test, SWIFT8 SID at YBCS,
HDG to ALT: Still not working
HDG to INTERCEPT: Seems to work now
INTERCEPT RADIAL: Doesn't work at all.

Will do more testing later.

**Comment by legoboyvdlp** [comment]
> HDG to ALT: Still not working
> HDG to INTERCEPT: Seems to work now
> INTERCEPT RADIAL: Doesn't work at all.

Those aren't supposed to work yet, if you want to make them work, you'll need to get in touch with James Turner, but thanks. I'm interested in making sure existing functioning working normally

**Comment by legoboyvdlp** [comment]
Although in that specific situation -- it flew the 030 to intercept; it just didn't intercept the radial; so it mightn't be that difficult, if you speak to James Turner about it, maybe he can look at it sometime. 

~~I identified one issue -- it doesn't always sequence T-P correctly when the angle to the direct-to waypoint >= 90 degrees, therefore the current-wp should be set to the direct-to waypoint, not T-P~~

**Comment by merspieler** [comment]
fgfs-20220514211955
Not quite sure what happened there...
Flying SWIFT8 departure again, this time quite heavy so I've intercepted the radial to climb to 4000'.
The next wpt jumped to SWIFT but the FD still showed a left turn...
DIRTO SWIFT solved that...

**Comment by legoboyvdlp** [comment]
My guess would be that it doesn't like intercepting a altitude --> real waypoint course. Internally as I recall, it just uses lat, long 0,0 as you can see when you use PLAN mode. But again you need to show this to James Turner. It would probably be better to test this on a "normal" airport!

**Comment by merspieler** [comment]
Loading the following fpln from the init flightplan, the STAR got inserted twice...
`EDDM INPU3E INPUD Y102 UPALA DCT EDDN`

**Comment by legoboyvdlp** [comment]
> Loading the following fpln from the init flightplan, the STAR got inserted twice... `EDDM INPU3E INPUD Y102 UPALA DCT EDDN`

Can you send me the simbrief .XML or flightgear .XML file please?

**Comment by merspieler** [comment]
[A320-family-simbrief.xml.txt](https://github.com/legoboyvdlp/A320-family/files/8695099/A320-family-simbrief.xml.txt)
That's the file from the export dir...

More things that popped up during that flight...
fgfs-20220515133029

The FO ND didn't show any route until I've changed mode forth and back.

Since it didn't contain an arrival for EDDN, I've selected the DKB arrival. Since that would have been a major detour, I've then removed the DKB and following wpt... I didn't know, that the temp fpln gets shown now... unfortunately it kept showing event tho I've inserted the changes into the active fpln. Interestingly this only happened on the Capt ND... maybe due to the fact that at the time of the change the FO ND didn't show anything...

**Pull request merged**
