### PR TITLE
Better AP Disconnect Sound

### PR DESCRIPTION
**Pull request by FurryMLG**
### Description of Changes
I Added a Better Autopilot Disconnect Sound, Taken from the JMaverick A330

### Checklist:

* [x] My changes follow the Contributing Guidelines. 
* [x] My changes implement realistic features. 
* [ ] Please have a main Developer test my changes before merging.

### CODE REVIEW

**Comment by merspieler** [comment]
Please describe why this sound should be better.
I've been going back and forth between the old, the new and videos such as [this](https://youtu.be/5MGtvPxvqlQ?t=350) and at least to me, the current one sounds closer to the real thing.

If I remember correctly, our version has been created to specification of the original sound.
@Octal450 touched the file last, he can probably tell more.

**Comment by FurryMLG** [comment]
Well Simply put, It has a better feel to it. It feels more immersive imho. And From watching [this](https://www.youtube.com/watch?v=xoz7aGTLMbg) it seems to be better. It's the reverb, and also the fact that the new sound was recorded from the actual aircraft.

**Comment by merspieler** [comment]
Reverb shouldn't be in the sound... cause you don't know in which environment the sound is played, in the end you get twice the reverb

**Comment by legoboyvdlp** [comment]
There are two problems with this:

Firstly, it does not preserve the behaviour - there is one sound that plays once, with a 'soft' disconnect, and another sound that plays repeatedly, with a 'hard' disconnect. This pull request breaks that functionality

Secondly, the sound does not reflect the real sound:

image

Compare the spectrogram of the current sound to that of your sound:
image

image

We can see that the current sound has distinct frequency pulses, while the replacement sound has a very confused frequency spectrum, with several harmonics that should not be there. Furthermore, the timing of the replacement sound is incorrect as it should be made up of five pulses of 40ms duration, while the replacement sound seems to have three pulses with a total of 250ms.

So, this sound does not bring any improvement over the current sound, and in several key ways is not accurate, therefore this pull request cannot be accepted.

**Pull request closed without merging**
