### PR TITLE
Use compositor lights for strobes and nav lights if available

### PR DESCRIPTION
**Pull request by ltoenning**
### Description of Changes

erik did some work to combine ALS procedural light and Compositor lights [[1]](https://wiki.flightgear.org/Howto:Add_aircraft_lights#Combined_ALS_procedural_lights_and_Compositor_lights). The solution should also be backward compatible with >= 2020.3.12 [[2]](https://forum.flightgear.org/viewtopic.php?f=47&t=40168&p=397777#p397840).

This pull request implements the method for the nav and strobe lights. 

If I have seen correctly, the light-manager.nas only calculates the light reflection on the ground for the nav/strobe lights. Therefore, if the compositor is available, it should be disabled.

Maybe the light parameters (direction, attenuation etc.) aren't 100% correct and ideal for now. But they were satisfactory for me so far ;)

### Screenshots (optional)

(Unfortunately, the GIF is  not showing the strobes double flashing...)

Peek 2022-04-02 23-57

### Checklist:

* [ X ] My changes follow the Contributing Guidelines. 
* [ X ] My changes implement realistic features. 
* [ X ] Please have a main Developer test my changes before merging.

### CODE REVIEW

**Comment by legoboyvdlp** [comment]
> erik did some work to combine ALS procedural light and Compositor lights
> If I have seen correctly, the light-manager.nas only calculates the light reflection on the ground for the nav/strobe lights. Therefore, if the compositor is available, it should be disabled.

Correct. The ALS procedural light is the illuminated point sprite. The Compositor light is the light that shines on the ground. 
The ALS so-called "light manager" controls what we call "lightspots", which are **also** the light that shines on the ground.

So, ideally, if we have version 2020.4 or later it should use Compositor; if 2020.3 it should use the light manager. If a version check was added to the init() function of the light manager that should be sufficient. There is no need for a version check for the Compositor lights because they are ignored in 2020.3.

Thanks for the pull request, it looks excellent. I'm not able to test + merge this because of Intel drivers unfortunately not working with the latest version of FlightGear.
@captb or @merspieler ?

**Review by merspieler — CHANGES_REQUESTED** [review]
Thanks you very much.
Looks great.
I've only noticed one minor detail, the tail strobe double flashes right now, that's now the case.
See https://github.com/legoboyvdlp/A320-family/blob/dev/Nasal/Libraries/libraries.nas#L30 for the flash pattern in the current implementation

**Comment by ltoenning** [comment]
Thanks, the tail strobe was indeed using the wrong property. Should be fixed.

**Review by merspieler — APPROVED** [review]
Thanks, looks good.

**Pull request merged**
