### PR TITLE
Merge FMGC

### PR DESCRIPTION
**Pull request by legoboyvdlp**
Adds support for flightplan in the MCDU.

@merspieler I'm thinking we should merge this asap, so Hayden can use the flightplan as a base for his rewrite. What do you think?

I know it is still only at alpha test stage, but it is functional, and I think, I have removed most of the bugs.

### CODE REVIEW

**Comment by legoboyvdlp** [comment]
And sorry for the merge dev commits - I can run a rebase to remove them just before merging and push -f...

**Comment by legoboyvdlp** [comment]
I just want to fix the ARRIVAL DIST thing but otherwise I think most is fine?

**Comment by legoboyvdlp** [comment]
What is also broken right now is the adding of discontinuities when inserting wpt - it should but doesn't.

**Comment by merspieler** [comment]
I'm happy with merging... and go ahead and rebase it, before.

Maybe make an announcement in the forum, that this change happened so ppl can decide if they want to stick to the current version or update to the merged one.

**Comment by legoboyvdlp** [comment]
Not sure why anyone would but ok 😂

**Comment by mattmaring** [comment]
Cool, once I finish up a few things I'd like to merge my branch into dev as well (after you do the FMGC), if that is ok with you two? I've changed quite a bit in the mcdu.nas and mcdu.svg, so I would prefer to only manually merge them once. Then we can both work off the new copies :)

**Comment by legoboyvdlp** [comment]
I merged the one conflict way back - since then it appears that our changes haven't conflicted in the .svg (which is a pain to merge)  so that's good. ;)

**Comment by merspieler** [comment]
Ready to merge?

**Comment by legoboyvdlp** [comment]
no

**Comment by legoboyvdlp** [comment]
DIRTO functional and arrival distance is next on list, then should be fine :)

vertrev needs merge first, then interface with hayden's work.

**Comment by merspieler** [comment]
I'm still getting `NOT ALLOWED` on the DIRTO page.

Another thing I've noticed, the remaining distance seems to include the GA-procedure

**Comment by legoboyvdlp** [comment]
Thx,

Dirto isn't finished yet but entering point manually works well, will check the arrival distance.

The algorithim to add new waypoints needs fixing, should delete intermediate waypoints if it already exists, same for dir to. Otherwise, it is very good right now I think :)

**Comment by mattmaring** [comment]
I've noticed that in situations where the go around fix is far from the airport, the arrival distance calculation includes this fix, so the speed is not dropping from 250 to VLS (flap 0). For instance KCVG 36C ILS arrival, with go around fix NEATS (flightPlanController.arrivalDist in console):



Issue lies on FMGC.nas line 233:
if (flightPlanController.num[2].getValue() > 0 and getprop("/FMGC/flightplan[2]/active") == 1 and flightPlanController.arrivalDist <= 15) {

I'm thinking either flightPlanController.arrivalDist should correspond to the distance excluding the go around procedure, or we need a separate variable to do that. Thoughts?

**Comment by merspieler** [comment]
I've noticed that too...

**Comment by legoboyvdlp** [comment]
Anyone know if it includes the go around or not?

**Comment by mattmaring** [comment]
Pg. 16 of this document seems to suggest its based off of RED ALT ("it-autoflight/settings/reduc-agl-ft") rather than distance: http://www.smartcockpit.com/docs/Airbus_Descent_Monitoring_1.pdf.

**Comment by legoboyvdlp** [comment]
@merspieler I believe that is everything I have to do, right now DIR TO is unstable as it doesn't work very well on SID / STAR waypoints. Arrival dist is still buggy. But the main thing is it works, doesn't crash, and flyable.

Could you review it, and approve it if you can't find other bugs so the merge button is enabled?

**Comment by merspieler** [comment]
will do

**Comment by merspieler** [comment]
Something seems to be broken here.
I've overflown the waypoint of the SID (GIVMI departure from EDDM) directly (distance showed 0.0NM) but the plan doesn't advance to the next point.

**Comment by legoboyvdlp** [comment]
Right, will check, can you tell me which SID code + rwy please? thanks.

**Comment by merspieler** [comment]
EDDM 26L GIVM6S  
and  
YBCS 15 SWIFT8  
are the ones I've tested.

**Review by merspieler — APPROVED** [review]
Looks goot

**Pull request merged**
