### PR TITLE
Mcdu

### PR DESCRIPTION
**Pull request by mattmaring**
I'd like to at least get the current MCDU bug fixes into master as soon as possible, since it is possible to brick the MCDU currently in the dev branch.

Not sure about your vertical phases though...

### CODE REVIEW

**Comment by legoboyvdlp** [comment]
- If you modify the coordinates in IRS INIT, your coordinates will disappear and be set to zero on the INITA page.

image

Or else, it is to do with flightplan sequencing, I am not sure...


- I want to check the c.g. according to the weight and balance manual on the FUEL PRED page. 

- VLS is, for safety reasons, always limited to >= VMCL. It is 113 knots for the A320-200: see https://www.theairlinepilots.com/forumarchive/a320/a320-limitations.pdf

The reference in the FCOM is 110 knots for VMCA, so therefore the correct value  is 113 knots rather than 108 knots.

- If we switch from PROG to F-PLN, the asterisk is not hidden:
image

- Nasal runtime error: non-numeric string in numeric context: ''
 1205.65 [ALRT]:nasal        at C:/Users/redpa/Documents/FlightGear/Custom Aircraft/A320-family/Nasal/MCDU/PERFAPPR.nas, line 14
 1205.65 [ALRT]:nasal        called from: C:/Users/redpa/Documents/FlightGear/Custom Aircraft/A320-family/Nasal/MCDU/MCDU.nas, line 215
 1205.66 [ALRT]:nasal        called from: , line 1

**Comment by legoboyvdlp** [comment]
Also:

image


This one is a bit funny 😃

**Comment by mattmaring** [comment]
Uhh, not sure on the IRS INIT, doesn't happen to me. It is based on wp[0] of the flight plan, if that is helpful at all.

Similar with temp, I can't replicate that. Do you remember what values you entered?

Already fixed the prog issue (and some others)

I'll take a look at VLS, can do the min easily, but not sure which chart I used for the VLS. Might take a lot of work for that one given I've computer regression formulas...

**Comment by mattmaring** [comment]
Just thinking, the coordinates in the INITA are not described in the FCOM I have. I don't even really know which coordinates they should correspond to (or even if they should be displayed!):
Screen Shot 2020-04-19 at 5 41 22 PM

The PERF pages are the newer ones in this FCOM, so I would think ^ is the newer INITA, but I'm not sure.

**Comment by legoboyvdlp** [comment]
Ok - I'll take a look in the Smith Thales manual now for you.
Don't worry about the VLS being >2 knots in that case, that's minor and can wait till later / be ignored :)

**Comment by legoboyvdlp** [comment]
The error with the coordinates is to do with the flightplan. I'll fix that...

**Comment by legoboyvdlp** [comment]
I think the nasal error was when I accidentally clicked the line select key with an empty scratchpad.

And yes, you are right. That is indeed the new INIT A. The Smith Thales manual is from 2002, the FCOM is from 2012. So where they contradict, I suppose its probably better to go by the latter.

**Comment by legoboyvdlp** [comment]
The INIT FUEL PREDICTION page still allows input on R3 even after the prompt FUEL PLANNING disappears.

Something has broken in the flightplan, since you can no longer select the departure runway:

image

**Comment by legoboyvdlp** [comment]
Just had a full test flight and apart from the minor things above, everything else works fine :)

Thank you again.

**Comment by mattmaring** [comment]
FUEL PRED fixed.

I would need more information of the flightplan breaking, it is working fine for me...

**Comment by legoboyvdlp** [comment]
Seems like the minimums / approaching minimums sounds aren't triggering here. I had BARO 226 feet, and certainly never heard them? 

Otherwise, I didn't notice anything else on my test flight - everything else working absolutely fine - nice work and thanks very much again!

I will check the flightplan, I think that might be on me, and will correct it if I can.

**Comment by mattmaring** [comment]
I'll look at the minimums. I'm not so good with xml, so I'm sure I messed up something :)

**Comment by mattmaring** [comment]
I'll need help looking at this one:
Screen Shot 2020-04-20 at 12 42 11 PM
I tried making these changes and now they go off continuously...

**Comment by legoboyvdlp** [comment]
Does /instrumentation/pfd/minimum have a default value?

Maybe you'd need a condition to disable the sound if they are not set in the MCDU?

**Comment by Octal450** [comment]
Or just make the default value some absurd number like 9999999 when its not set

Is this all pushed? I can take a look at that

Kind Regards,
Josh

**Comment by mattmaring** [comment]
The default values are -1, I can push that change if you want.

**Comment by Octal450** [comment]
OK, I will look into this shortly, almost finished with work

Josh

**Comment by mattmaring** [comment]
Ok, it works as long as the baro/radio isn't the same height as another announcement (i.e. 500/400/etc). Not sure what the precedence of the callouts is, but that probably needs changed.

**Comment by legoboyvdlp** [comment]
Awesome, thanks! @Octal450 pls confirm, and I'm happy to merge therafter :)

**Comment by Octal450** [comment]
Done with work... checking out now!

**Comment by Octal450** [comment]
@hayden2000 Found the problem, fixing now.

**Comment by Octal450** [comment]
a43aad1 fixes this

Kind Regards,
Josh

**Review by Octal450 — APPROVED** [review]
NIce work @hayden2000 @legoboyvdlp

**Pull request merged**
