### PR TITLE
Second web mcdu with "photorealistic" appearance

### PR DESCRIPTION
**Pull request by rumpelrausch**
Web mcdu with a choice of two variants: The previous, abstract one and a more realistic looking version.

### Description of Changes
The html at the original URL is now a chooser between both variants.
The original web mcdu code is unchanged (but moved into a subfolder).
This should provide seamless migration to users if needed.

### Screenshot (alternate variant)
image

### Image sources:
- MCDU panel\
  Blender render created from scratch. No foreign images used.
- Glass dirt overlay\
  Shameless copy from 3D branch.

### Checklist:
...hope I did it all correctly; It's my first Github PR.

* [x] My changes follow the Contributing Guidelines.
* [x] Commit message style: [Conventional Commits](https://www.conventionalcommits.org/)

### CODE REVIEW

**Comment by legoboyvdlp** [comment]
Wow - that's very impressive. Nice work!  I'll try it out

**Comment by merspieler** [comment]
Looks good from my side.

**Review by merspieler — APPROVED** [review]
Code looks fine.

Only thing that could be done better next time from what I've seen is move the old mcdu.html to the new dir and commit that to keep the history of that file clean

**Comment by rumpelrausch** [comment]
AFAIK there's no way to move a file and keep its history in git.
https://git.wiki.kernel.org/index.php/GitFaq#Why_does_Git_not_.22track.22_renames.3F

If someone knows how to _easily_ circumvent this without hacking the whole history I'd definitely like to learn how.

From git's point of view, moving a file is a modification of structure, and git (as Linus wanted it) focuses history on structure, not files. If we want seamless integration for existing users (probably using bookmarks) we will either have to modify outside the web app (extend the menu) or lose history of that file.

**Comment by merspieler** [comment]
Actually `git mv` does keeps somewhat the history.

Git blame shows the old commit, from before the move, git log -- <path> doesn't show the initial file from bevore the move tho,

I was taught to keep structure and code changes to separate commits... a best practice I've kept.

Was just a comment what could improve things, nothing that would stop this PR.

@legoboyvdlp you wanted to try it too? Or should I just merge it?

**Review by legoboyvdlp — APPROVED** [review]

**Pull request merged**
