### PR TITLE
Moisture and spray effects + brakes temp calculation improvement

### PR DESCRIPTION
**Pull request by vezza**
Added engines moisture effect, engines spray effect, brake temp modulation according to weight (gear/gear[n]/compression-norm), removed brakes temp increase on thrust

### Description of Changes

Added engines moisture effect, engines spray effect, brake temp modulation according to weight (gear/gear[n]/compression-norm), removed brakes temp increase on thrust

### Checklist:

* [x] My changes follow the Contributing Guidelines. 
* [ ] My changes implement realistic features. 
* [x] Please have a main Developer test my changes before merging. 
* [ ] My changes are ready for merging.

### CODE REVIEW

**Comment by legoboyvdlp** [comment]
@vezza 
I have invited you to become a contributor. Please make sure you use branches etc, thanks, for major changes. For bugfixes and minor changes, use of dev directly is fine.

**Comment by legoboyvdlp** [comment]
I am unsure about the moisture effect. Surely it should go by rain (i.e. standing water on the runway getting sprayed by engine thrust), rather than humidity? Or is it attempting to replicate something other than spray of water on the runway?

Also, I think it should account for reverse thrust and blow water forwards -- and currently this is happening with reverse thrust?
image

I see moisture at the front of the engine, but it is getting blown backwards. Probably the life of the particles needs to be greatly reduced so it is not blown backwards but only is shown at the front of the engine.

Edit - also, when I cancel reverse thrust, there appears to be a giant burst of spray!

**Comment by vezza** [comment]
Thanks for the invitation... my skills are not the best but every day I'm learning something new... anyway I hope to be useful. As for the spray's I'll try to fix them... I'm trying to add water spray's when the runway is wet. Moisture instead should appear according to relative umidity.

**Comment by legoboyvdlp** [comment]
There is a fatal exception now - properties must not start with numbers but with only alphabetic characters.

**Comment by vezza** [comment]
I see... looking at it but at the moment I can't find where is the problem...

**Comment by legoboyvdlp** [comment]
Does the simulator start for you?

**Comment by vezza** [comment]
No, I'm getting this message: '1' found in propertyname after ''
name must begin with alpha or '_'

**Comment by legoboyvdlp** [comment]
Yep, same here.

**Comment by vezza** [comment]
Fixed the bug... looks fine here, probably it needs some little tweaking on the engine's reverse spray position and looking, also engine moisture is not the best but according to my knowledge at the moment I can't do something better. Anyway please test and comment as usual... bye!

**Comment by legoboyvdlp** [comment]
I agree that the particles could be improved, but the rest looks great and for now the particles are fine. Thanks again!

**Pull request merged**
