### PR TITLE
Canvas based livery system

### LINKED ISSUE #246: Bug - Unable to change liveries
**Describe the bug**
It is not possible to change liveries at all with the 3D branch aircraft. It initializes with an "unpainted" livery; if you try to change it, the simulator freezes and crashes to desktop. The feature works flawlessly in the dev branch.

**To Reproduce**
Spawn in with the 3D branch aircraft. Try to change liveries through the menu. Crash to desktop.

**Expected behaviour**
Not crashing and changing the livery.

**System (please complete the following information):**
 - OS: Lubuntu 20.04
 - FlightGear version: 2020.3.9
 - A320 Version: 3D branch

**Additional context**
It doesn't happen with the dev branch. Something got messed up somewhere in the 3D branch and I suppose it will eventually make it into dev.

### PR DESCRIPTION
**Pull request by merspieler**
### Description of Changes

Replaces the old livery system with a canvas based one.

Advantages:
* Way faster loading
* Dynamic display of things like dirt and ice, without it being baked into the livery
* Seems to work better on lower end machines, see #246 

There might still be some issues so please check carefully.

NOTE: Requires an up-to-date flightgear (as of 2021-07-31) due to a fix to a SIGSEGV.

### Bugs fixed (if any)

This would fix #246 

### Checklist:

* [x] My changes follow the Contributing Guidelines. 
* [ ] My changes implement realistic features. 
* [x] Please have a main Developer test my changes before merging.

### CODE REVIEW

**Comment by legoboyvdlp** [comment]
Todo:
- Add version checks
- After anisotropy fix is merged to next, uncomment anisotropy
- Confirm correct operation on Macs

**Comment by Octal450** [comment]
Whats performance hit like?

Kind Regards,
Josh

**Comment by merspieler** [comment]
I didn't seen any real performance difference, on a mid range PC tho.. low end with iGPU might differ.
But there shouldn't really be much/any as the canvas is only updated when you switch the livery

Loading performance is greatly improved tho

**Comment by legoboyvdlp** [comment]
I see no difference either!

**Comment by Octal450** [comment]
Sweet! I will test later!

J

**Comment by merspieler** [comment]
Make sure, you update your fg first... lego did a fix for the SIGSEGV...

**Comment by legoboyvdlp** [comment]
either update your 2020.4 or else use 2020.3

**Comment by Octal450** [comment]
I am always on the latest next! Seriously! 

Kind Regards,
Josh

**Comment by legoboyvdlp** [comment]
So anisotropy is fixed + added . Version check is added. It works on Mac. Can we go ahead and merge? Or fix NEOs ? @merspieler

**Comment by merspieler** [comment]
I'll do the neos and then merge.

**Comment by merspieler** [comment]
Found a bug, that I need to fix before merging...
Will do so either in the evening or tomorrow.

**Comment by merspieler** [comment]
@legoboyvdlp please check and if fine, merge

**Pull request merged**
