### PR TITLE
Remade Checklist 

### PR DESCRIPTION
**Pull request by AAL5665**
I have remade the most checklists for beginners who have never used the aircraft before.

### Description of Changes
I have add condition check to verify a requirement to be enabled
Renamed some checklist
Added more checks

### Screenshots (optional)
fgfs-20210617093917
fgfs-20210617093920
fgfs-20210617093945
fgfs-20210617093931
fgfs-20210617093951

### Checklist:

* [x] My changes follow the Contributing Guidelines. 
* [ ] Please have a main Developer test my changes before merging. 

Work In Progress
[A32X-Checklists.xml.zip](https://github.com/legoboyvdlp/A320-family/files/6669134/A32X-Checklists.xml.zip)

### CODE REVIEW

**Comment by merspieler** [comment]
I close this PR cause of 2 things:
1st, you try to merge the 3D branch into dev... we won't do that. Please make a feature branch off of dev and open a pull request against the dev branch.
2nd: If you want detailed instructions DO NOT use the checklists. The checklists are made after the original ones.
For step by step instructions please make it a tutorial.

**Comment by AAL5665** [comment]
okay

**Comment by AAL5665** [comment]
how should I setup the into and from?
and what is meant by making it a tutorial? @merspieler

**Comment by legoboyvdlp** [comment]
I mean, the checklists don't exactly have to match the checklist since there is a proper checklist available in the Canvas QRH and also printed on the 3D model. The checklists are useful for the flows as well found in the FCOM. The checklists in the real aircraft are just used to check you didn't forget anything - but the checklist feature in FlightGear can also be used with the procedural flows, considering there is an actual checklist available elsewhere.

I can't remember when we last discussed this but its just a thought I had and I'll let you decide @merspieler 

I also like the idea of tutorials. Refer to FGData/Docs/README.tutorials and https://wiki.flightgear.org/Tutorials

**Comment by merspieler** [comment]
There are addons like [this](https://gitlab.merspieler.tk/fly/flight-gear-copilot) which depend on the checklists matching the real ones.

I'm not completely opposed to having flows as "checklists", but they should be their own thing, not the actual checklist.
So have a "checklist" `After landing flow` which contains more than the checklist.

Still I'd prefer to have such things as tutorial as it walks the user through it and you can even explain things (using the marker thingy).



> how should I setup the into and from?

(I assume you don't really know how to use git)
On the top right of this page you find the a button labeled `Fork`
If you click on it, github will fork the repo for you (you've then got your own copy of the repo under your own name)
There you can either edit the files on the dev branch directly (open the file and the click edit)
or you can branch off.

If you know, how to use git you can always clone your fork or add it as a remote onto the already cloned repo.
Then do you work there and push to your own fork.

Once that's done, github will probably already offer you to merge the branch.

[Here](https://seafile.merspieler.tk/f/f9fa569106de4981a1e5/?dl=1) you can find a very old tutorial file where I've started doing a tutorial back in 2018.

If you want to try that you've got to add `<tutorials include="A32X-Tutorials.xml" />` in the `A320-main.xml` under `<PropertyList><sim>`

You might as well want to take a look at the CRJ700 tutorial, as another example.

**Pull request closed without merging**
