### PR TITLE
Moving external ground stuff to ground services menu

### PR DESCRIPTION
**Pull request by jelovac**
### Description of Changes

Implementing feature request #151 

### Change log

Moved the following items from Aircraft configuration canvas to Ground Services canvas:

- Landing gear chocks
- Enable External Power Box
- Enable External Air
- Yellow HYD Hand Pump

Ground services canvas change:

- reordered and regrouped the elements semantically by their usage
- merged landing gear chocks under a single checkbox

### Screenshots

Before:

a320-menu-before

After:

a320-menu-after

### Checklist:
* [x] My changes follow the Contributing Guidelines.
* [ ] My changes implement realistic features. 
* [x] Please have a main Developer test my changes before merging.
* [x] My changes are ready for merging.

### CODE REVIEW

**Comment by merspieler** [comment]
Looks good. Thanks

**Comment by jelovac** [comment]
Hi @legoboyvdlp, @merspieler,

Found a bug related to the merging of the chocks under a single checkbox.

Basically I found out today that when you connect pushback truck that the nose gear chocks are automatically removed if enabled.

Main gear chocks are unaffected and since we do not have an individual checkbox anymore we end up cycling between nose gear and main gear.

So far I tracked down the issue to here: autopush-config.xml

`<chocks	alias="/services/chocks/nose"/>`

Not sure what would be the proper way to fix this.

**Comment by merspieler** [comment]
Use a single prop for all gears and modify the autopush's alias accordingly

**Comment by jelovac** [comment]
Ok, can you reopen the issue #151?

**Pull request merged**
