### PR TITLE
Added refuel dialog

### PR DESCRIPTION
**Pull request by merspieler**
Signed-off-by: merspieler <merspieler@airmail.cc>

### Description of Changes

Added refuel dialog, functionality missing.

Control properties are in `/controls/fuel/refuel/`

### TODO
* [x] Set correct max fuel at top of file
* [x] Make `Test` switch spring loaded
* [x] Keep in/decreasing preselected fuel when kept holding
* [ ] Limit power supply when on `DC HOT 1`
* [x] Connect fuel levels
* [ ] Deactivate when moving/flying?

### Checklist:

* [x] My changes follow the Contributing Guidelines. 
* [x] My changes implement realistic features. 
* [ ] Please have a main Developer test my changes before merging. 
* [x] My changes are ready for merging.

### CODE REVIEW

**Comment by legoboyvdlp** [comment]
Please remember that SVG circles don't work - make the circle then use the "Convert Selected Object to Path" tool in the F2 edit mode, top toolbar :)

**Comment by legoboyvdlp** [comment]
Please:
* fix circles
* fix the INC / DEC not showing up

Thanks

**Comment by merspieler** [comment]
I forgot about pts...
Fixed the circles... they are now squares :D

Not sure what's wrong with teh INC DEC switch... maybe it is due to the fact, that it uses gradients...
I'll see if I can do something else neat...

Tho i might give out a call for contribution for a  more talented graphics person than me to give it a more realistic touch.

I'll fix the test button too.

**Comment by merspieler** [comment]
Once refueling is done, the END light should come on... apart from that (haven't seriously checked the logic due to version...) it should be okay for merge

**Pull request merged**
