### PR TITLE
Emesary PFD

### PR DESCRIPTION
**Pull request by legoboyvdlp**
@Octal450 @merspieler would appreciate testing to make sure I didn't miss any obvious nasal errors, also for performance (improvement or otherwise)

### CODE REVIEW

**Comment by Octal450** [comment]
Will test.
Please be aware of an updated property on the 3d branch, the sidestick indicator should be slewed with:
/fdm/jsbsim/fbw/roll/a-i-pfd
/fdm/jsbsim/fbw/pitch/e-i-pfd

Also i think the throttle and ap stuff may have changed

If I merge it into 3D i'll take of this but if not, figured I'd let you know.

Kind Regards,
Josh

**Review by merspieler — APPROVED** [review]
Looks good to me

**Review by Octal450 — APPROVED** [review]
No ability to change rate?
Otherwise looks good, nice job.

Fyi on my dv7 i7 720QM + GT230M there is no FPS improvement.

**Comment by legoboyvdlp** [comment]
@Octal450 as far as I know, I fixed all the merge things for 3D now, autopilot and thrust and fadec etc. And the only change I didn't do is the a-i-pfd thing. I couldn't find that property. Maybe you didn't push that yet?

**Comment by Octal450** [comment]
@legoboyvdlp its not pushed yet, its in the changed FBW. I will make that change. Thank you!

Kind Regards,
Josh

**Pull request merged**
