### PR TITLE
Add RMP dialogs and enable RMP3

### PR DESCRIPTION
**Pull request by merspieler**
Signed-off-by: fly <merspieler@airmail.cc>

### Description of Changes

Implements #13 

### Checklist:

* [x] My changes follow the Contributing Guidelines. 
* [x] My changes implement realistic features. 
* [ ] Please have a main Developer test my changes before merging. 
* [x] My changes are ready for merging.

### CODE REVIEW

**Comment by legoboyvdlp** [comment]
I take it its not a fuelling dialog - going to remove those extra nodes that are still there from the old dialog.

**Comment by merspieler** [comment]
Yep, sorry... overlooked them

**Comment by legoboyvdlp** [comment]
Could you make the knobs work...?


Also, might I suggest taking a screenshot of the actual panel and using that - as well as being more hi-res (the current one is too tiny imo) it also looks better :) It _would_ need to be straight-on though, perpendicular to the panel and centered correctly.

**Comment by merspieler** [comment]
Dam it... i knew i've had forgotten something.

Unfortunatly, FG doesn't support embedded pngs... I've tried that.

As for the size, scaling it up is no problem...

**Comment by legoboyvdlp** [comment]
Great, thanks.

I think the idea is you vectorize the screenshot, not sure how well it works but certainly thorsten has done it and it looks very nice?

**Comment by legoboyvdlp** [comment]
Probably some of these tools might work
?

https://www.google.com/search?rlz=1C1CHBF_en-GBGB784GB784&sxsrf=ACYBGNRRCmn5qZS8di-MDjxgwt3SMGiVVg%3A1575486150207&ei=xgLoXdalDImh1fAP9sKQoAo&q=how+to+vectorize+a+png+to+svg&oq=how+to+vectorize+a+png+to+svg&gs_l=psy-ab.3..33i22i29i30l10.4037.11122..11196...8.1..0.98.2625.36......0....1..gws-wiz.......0i71j35i39j0i67j0i131j0j0i273j0i20i263j0i22i30.485inGUNP3I&ved=0ahUKEwjWoNOi15zmAhWJUBUIHXYhBKQQ4dUDCAs&uact=5

**Comment by merspieler** [comment]
I haven't got any really good results... tho I'm fine with how it looks... so I won't do anything... in the end (at least in my opinion) the dialog is just a backup for the virtual cockpit

**Pull request merged**
