### PR TITLE
Brake system improvements

### PR DESCRIPTION
**Pull request by vezza**
Adding:

brakes temperature;
brake temp indication in LOWER ECAM wheels page;
Brake fans switch on main panel;
Brake Hot light on main panel;
"BRK FAN" ECAM message;
### Bugs fixed (if any)

Todo - Brakes temperature #31

### Checklist:

* [ ] My changes follow the Contributing Guidelines. 
* [ ] My changes implement realistic features. 
* [x] Please have a main Developer test my changes before merging. 
* [ ] My changes are ready for merging.

### CODE REVIEW

**Comment by legoboyvdlp** [comment]
It _should_ be fine - but I need to make sure TH-555 is happy with it.

**Comment by legoboyvdlp** [comment]
I think we should tune it a little:

> We usually only use it on taxi-out. Temperatures up to around 450°C after landing usually cood down to well below 300 in the standard turnaround time [ between 30 minutes and an hour I guess], a tiny bit more if you release the brakes once the chocks are in place. If the temperature reaches 500°C or higher we should use the fan and to not stick to the minimum 5 minutes according to my company.

Also, the sensors may underread significantly (i.e. it cools down quickly to a temperature maybe 50 deg below brake temperature) then it cools down proportional to the actual brake temperature, getting closer as the brakes actually do cool.

**Comment by legoboyvdlp** [comment]
The heating up maybe could be a little stronger, but not much, RTO at MTOW reached 500 degC which probably is fine. However, the cooling down I think is too fast.

The indications look good.

Also, when the aircraft is holding the aircraft against full thrust, it still cools down?

**Comment by vezza** [comment]
Yes, it needs to be tuned... I'll look if I can do something about it. What about the Brk_fan_on indication light? Do you know il blue is the right color? Thanks for your comments.

**Comment by legoboyvdlp** [comment]
I think it is meant to be a white LED.

**Comment by vezza** [comment]
Changed the brk_fan_on indicator light color and tried to adjust brakes temperatures and cooling time... can someone please test and comment it? Thanks

**Comment by legoboyvdlp** [comment]
That's very good!
Just a couple things:
if cooling could be according to airspeed, and could be set to almost zero if the gear are retracted
if the effect of having the brakes on on the ground when stopped could be increased according to engine thrust total
and finally chocks should not affect the cooling - seems that cooling slows down a lot when the chocks are enabled.


(edit - can you make sure also that cooling can't drop below TAT? I didn't see this happen on any test flight but just in case?)
Other than that - fantastic!

**Comment by vezza** [comment]
Ok, I will try...

**Comment by vezza** [comment]
Are you sure that brakes temp is related to engines total thrust? I think that brakes temp is related to kinetic energy and if the aircraft is stopped kinetic energy is 0... Engine trust is counter balanced by tires friction to ground... what do you think?

**Comment by legoboyvdlp** [comment]
No, otherwise the aircraft wouldn't be able to move off, if it was the friction? 

Because, the brakes are providing friction against the wheels - stopping them from rotating, this means all the energy pushing forward (yes, the resultant force is zero meaning your kinetic energy is zero - however, you have thrust and what's making your resultant force zero is the force opposing thrust, which is friction in the brake pads.

**Comment by legoboyvdlp** [comment]
Actually - I think you are right. While there is (a large) amount of static friction, kinetic energy is zero) -- so you might have friction between the wheels but they won't heat up much. 

Maybe I need to investigate further, sorry.

**Comment by legoboyvdlp** [comment]
Yes - you are right, sorry - the kinetic energy is, actually, the main factor.

**Comment by vezza** [comment]
Ok, anyway I've tried to add a little bit of temp according to thrust... can you test it? Thanks

**Comment by legoboyvdlp** [comment]
Excellent, absolutely!

**Comment by legoboyvdlp** [comment]
Ok - 

For TAT you can use existing properties (i.e. the one shown on the ECAM) - no need to calculate it again.

Other than that, the code looks fine and I'll give it a test flight shortly.

**Comment by vezza** [comment]
Thanks for taking the time to test and comment... Well, to be true I've searched for the TAT in the property tree but didn't find it... At the moment I don't have a lot of time but one day I'd like to add a delay in the temperature's shown on the ecam (I've read that it takes a little bit of time for the sensors to read the temperature's variation)

**Comment by legoboyvdlp** [comment]
If you do please add it to the TAT sensor --> NOT to the display. Thanks.

**Comment by legoboyvdlp** [comment]
Checking and about to merge.

**Pull request merged**
