### PR TITLE
Option for showing weights in kgs

### PR DESCRIPTION
**Pull request by merspieler**
### Description of Changes
Display kgs or lbs depending on the users choice. Systems keep running on lbs.

### TODO
* [x] Lower ECAM
* [x] Upper ECAM
* [x] Dialog
* [ ] MCDU

### Bugs fixed (if any)
Solves #15 

### Checklist:

* [x] My changes follow the Contributing Guidelines. 
* [x] My changes implement realistic features. 
* [ ] Please have a main Developer test my changes before merging. 
* [ ] My changes are ready for merging.

### CODE REVIEW

**Comment by legoboyvdlp** [comment]
Excellent, thank you, let me know when it's ready for review!

**Comment by merspieler** [comment]
I've got no clue how to change the Fuel and Payload panel...
I think, it could be nice, to have a custom one, similar to payware, showing seats instead of weights....

As for the MCDU, you said, you want to rework it, would it make sense to wait with applying the changes there, until you're done with it?

**Comment by merspieler** [comment]
@legoboyvdlp any opinion on my comment above?

**Comment by legoboyvdlp** [comment]
probably best to change it, it must be consistent.

**Comment by merspieler** [comment]
okay...

I've got an about 3h train ride in a few days... i'll see if I can get a new payload dialog done there

for the MCDU, I'd prefer you to do it as I've never touched it before.

**Comment by merspieler** [comment]
I've merged and pushed it manually to fix #61 
Default was set to lbs for now and checkbox is commented out -> no change for the user except for the fix.

**Pull request closed without merging**
