### PR TITLE
Use 'Ctrl+E' to connect/disconnect external power

### PR DESCRIPTION
**Pull request by dg-505**
### Description of Changes
- Add the key binding for A320-main.xml
- Add an entry to the Aircraft Help Dialog
- Modify EXT PWR pushbutton tooltip in a320.flightdeck.xml to clarify wording, because the pushbutton does not _connect/disconnect_ the external power box, but instead it _activates/deactivates_ the power supply, if an external power box is already connected.

### Checklist:

* [x] My changes follow the Contributing Guidelines. 
* [ ] My changes implement realistic features. 
* [ ] Please have a main Developer test my changes before merging.

### CODE REVIEW

**Comment by Octal450** [comment]
I am not really sure I love this binding.

Is it because EXT PWR is nested away under too many clicks? Personally I think it should live in ACConfig.

Kind Regards,
Josh

**Comment by dg-505** [comment]
Huh?? I din't manually add the last three commits to this PR. And I have no idea where these "Merge remote-tracking branch 'refs/remotes/origin/dev' into dev" commits come from... How can I remove the three last commits from this PR and open a new PR just for my last commit?
Sorry for the mess.....

**Comment by Octal450** [comment]
You'd have to make a branch off before your other commit and then cherry-pick the commit you want over. There is no way to only merge certain commits from a branch via GitHub - has to be done locally. 

Let me run this past Semir and if it has his approval, I can merge the commit for you.

Kind Regards,
Josh

**Comment by dg-505** [comment]
Actually, it seems that I have messed up my git (again.....) I'm gonna close this PR, delete my fork and my local copy. Then I fork again and file a new PR..... seems to be the easiest way

**Pull request closed without merging**
