### PR TITLE
Chrono dme

### PR DESCRIPTION
**Pull request by legoboyvdlp**
### Checklist:

* [ ] My changes follow the Contributing Guidelines. 
* [ ] My changes implement realistic features. 
* [ ] Please have a main Developer test my changes before merging. 
* [x] My changes are ready for merging.

### CODE REVIEW

**Comment by merspieler** [comment]
Squash before mergin to get rigd of the Reverts?

**Review by legoboyvdlp — COMMENTED** [review]
- Formatting of clock.nas - please see formatting guidelines in contributing.nas. I will approve meanwhile. Testing the chrono_dme.

**Comment by legoboyvdlp** [comment]
The clock is not readable at all. The letters are black? 

The CHRONO switch on the FCU should be enabled.

Switch on lower right doesn't work, it goes to the first position, then is stuck. 

And the glare needs fixed.

**Comment by legoboyvdlp** [comment]
Reference:
image

image

Looks like its white text, and integ lighting illuminates the **background** with a bright blue light. 

My suggestion - revert to fd_complete.ac from _dev_ and start afresh?

**Comment by vezza** [comment]
Thanks for your suggestion but I prefer not to revert to fd_complete.ac dev at the moment because I'm not a 3D developer and it will takes me too much time to do everything again... maybe when I'll understand what is the problem... as for now I moved the lables on the clock body texture in order to show them. Now the clock and the chrono are working seems to work fine here...

**Comment by vezza** [comment]
Wait a moment the I've just realized now that the clock labels aren't backlighted... I think I'll be able to work out and revert to fd_complete.ac dev in the next few days...

**Comment by legoboyvdlp** [comment]
I sent a review on discord, it is quite lengthy, so a summary too :)

**Comment by vezza** [comment]
Sorry, I had to force push changes as I wasn't able to sort out how to merge fix conflicts...
The clock GPS/INT/SET mode isn't done yet (don't know if it is possible) anyway I think that it should be useful to have a working clock/chrono in the cockpit.
I've also enabled terrain_on_nd pushbuttons and fixed the UV mapping problem (doubled objects) and fixed some typo's (It should be autopilot/serviceable instead of autopilot/servicable isn't it?) ;
As for DDRMI dme's and Rudder trim display they should be working. Please test and report, thanks.

**Comment by legoboyvdlp** [comment]
Great - thanks!

**Comment by legoboyvdlp** [comment]
Minor thing - below one mile, the DME display should show zero.

**Review by merspieler — APPROVED** [review]
Looks great now, thanks.

From me, it's a go for merge.

**Pull request merged**
