### PR TITLE
Enable FPV functionality

### PR DESCRIPTION
**Pull request by sgilchrist123**
### Description of Changes
If user selects TRK-FPA, display FPV on PFD1 and PFD2. 

FPVs on PFD1 and PFD2 are based on ADR1 and ADR2 respectively.

FPV only displayed if ADIRS is aligned and available. If ADR1 or ADR2 is not available but ADR3 is, ADR3 can be selected via ATT switch on switching panel.

Based on FPV code from MD11 (as recommended by legoboy).

Also fixes bug with trk pointer - which always incorrectly displayed 0.

This is my first attempt at writing code for FlightGear. Merspieler suggested/encouraged me to give it a go and suggested this feature. Also provided feedback and suggestions on initial attempts. I have attempted to follow the same coding  style as existing code. Having said that I am still get my head around the best way to write code (eg when to get values from other Nasal objects rather than the property tree).

Unfortunately I don't have access to images of an actual FPV on a PFD - so I estimated the dimensions based on diagrams in the FCOM.

### Checklist:

* [x] My changes follow the Contributing Guidelines. 
* [x] My changes implement realistic features. 
* [x] Please have a main Developer test my changes before merging. 
* [x] My changes are ready for merging.

### CODE REVIEW

**Review by merspieler — APPROVED** [review]
Looks good

**Comment by merspieler** [comment]
@legoboyvdlp could you please check, that I haven't overlooked anything.

To me it looks all good, so if you don't find anything we're good for merge.

**Comment by legoboyvdlp** [comment]
Hello,

A couple of minor things:
- I'd like to take the FPV symbol from the MD-11 - it would be a bit closer to the actual one as seen in FSLabs A320 (their displays are rather accurate). In particular the green colour is too light and should be the same as the minimum pitch angle brackets directly below (-15 degrees).

- All the photo reference doesn't show a dimmed aircraft symbol with FPV. I suspect this is to do with software edition, but can't confirm this for definite. Unless there is photo reference for a gray aircarft symbol I would prefer to leave it undimmed because:
* This matches the available references
* And there is no reference to know exactly what "dim" means, if that makes sense?


image

image


Maybe a FPV failure flag would be good, in the situation where you have an air data problem? 


Thank you!

**Comment by legoboyvdlp** [comment]
An independent source has verified that while their FCOM mentions the dimming of the yellow outline, it does **not** occur on any of the A320s they have flown, ranging from 2 week old to 20 year old. It might potentially be a legacy from the A300 / A310.

**Comment by sgilchrist123** [comment]
Hi

Thanks. That's all great feedback. Very happy to make those changes. (Sorry for forgetting to mention in pull request that I also based dim feature on guesswork.)

Re the FPV flag, what do you think would constitute an air data problem? Just if there's an error light on relevant ADR PB switch? (Which would be my guess.) Or if it's a totally unrealistic value eg > 90 degrees or even something not overly unrealistic but perhaps worrying eg > 30 degrees?

The only thing I could find was this in the FCOM "In the TRK FPA mode, when the drift angle or flight path angle is not valid, an FPV flag appears." DSC-31-40 page 27 

The FCOM also refers to various situations where the FPV flashes. Is it OK to implement those later? I was thinking of trying my hand at implementing the FPD next (without having looked into how hard/impossible that would be for someone with my basic skillset). But very happy to fit in with your plans.

image

Cheers and thanks again

**Comment by legoboyvdlp** [comment]
>  I was thinking of trying my hand at implementing the FPD next

Sounds great 👍  :) 

Sure, the flashing can definitely wait. Indeed, if you want to get this merged sooner rather than later, I don't mind, it's fine to leave the entire warning flag for later!

Actually, now that I think of it, perhaps it is an IR feature rather than ADR. But the IR isn't simulated very well.

**Comment by sgilchrist123** [comment]
Hi

I've replaced the FPV with the one from the MD-11 and I've removed the code
to dim the fixed aircraft symbol on the PFDs.

I've committed the changes to my fork and I'm not certain but I think you
can accept them using my original pull request? (if you are so inclined) I
don't seem to be able to open a new pull request.

I will add the warning flag after trying my hand at the FPD.

Let me know if there are any issues.

Cheers

**Comment by merspieler** [comment]
>     * I'd like to take the FPV symbol from the MD-11 - it would be a bit closer to the actual one as seen in FSLabs A320 (their displays are rather accurate). In particular the green colour is too light and should be the same as the minimum pitch angle brackets directly below (-15 degrees).

That one is actually less accurate for Airbus, than what we had before.

in this [video](https://www.youtube.com/watch?v=JvZisfuCEyw&t=296) from an Qatar Airways sim, you can clearly see, that the  horizontal lines span a good bit more than the 5° pitch line (I know, that's an A330 but that doesn't make a difference in this case).

As you were saying FSLabs? The lines there are [clearly longer](https://www.youtube.com/watch?v=1IhzbfB-8pI&t=407)

According to [this video](https://www.youtube.com/watch?v=btPL-5f-aKk&t=1889) (done by an RL Airbus pilot) the tail of the bird should be at the base of the horizon when on a 3° glide path.

**Comment by Octal450** [comment]
You can just extend the lines out more then you can just change the width and realign using the offset of the circle, or move the outer 2 nodes by the same amount on each side
-J

**Comment by legoboyvdlp** [comment]
@merspieler any chance you could do the relevant changes to the .svg?

**Comment by merspieler** [comment]
sure.

I just can't add it to this pr so I've got to do that after it got merged.

**Comment by sgilchrist123** [comment]
I amended my local copy of .svg file to incorporate various
suggestions/references to videos etc but local dev environment screwed up
so I can’t test changes before committing. Might be able to get fixed
today. Not sure if there’s any point me sending you the file in
the meantime?

**Comment by merspieler** [comment]
sure, you can do that

**Comment by sgilchrist123** [comment]
Here you go - The guides in the Inkscape file are at the 5, 7 and 10 degree position - so you can test what the bird looks like at a -3 degree angle by treating the 10 degree line as zero (if that makes any sense).

I hope this works, like I said something has gone screwy with my local dev environment, so I haven't been able to test it in FlightGear.


[pfd.svg.zip](https://github.com/legoboyvdlp/A320-family/files/5267594/pfd.svg.zip)

**Comment by merspieler** [comment]
Looks way better now.

Only thing is, it acts up for me as well...
When loading that .svg, it is shown link you see it in inkscape...

**Comment by sgilchrist123** [comment]
Egads! What have I done?! I might need to start from scratch with totally
clean copies of the files. But might not get a chance until the weekend.
Getting slammed at work.

Sorry about this.

Cheers

**Comment by merspieler** [comment]
No worries mate, take your time.

**Comment by legoboyvdlp** [comment]
This should be good to merge once that is done :)

**Comment by merspieler** [comment]
@sgilchrist123 what's the status?

**Comment by merspieler** [comment]
merged manually

**Pull request closed without merging**
