### PR TITLE
Implementing state save between sessions

### LINKED ISSUE #69: Feature Request - Save aircraft state between sessions
**Describe the solution you'd like**

Save state of certain things and load them on startup.
List (non-exhaustive):
* Fuel level
* Eng oil level
* Bat charge (accunt for discharge while fg is not running?)

@legoboyvdlp what would be the best way to implement this?

**Additional context**
First step towards #36

### PR DESCRIPTION
**Pull request by merspieler**
Signed-off-by: fly <merspieler@airmail.cc>

### Description of Changes

Added an option to the acconfig to save the state.
Usage to add more properties is as simple as adding them to the array on top of `Nasal/Systems/save.nas`.

I'm not 100% happy with the label in the dialog tho...

Implements #69 

### Checklist:

* [x] My changes follow the Contributing Guidelines. 
* [x] My changes implement realistic features. 
* [ ] Please have a main Developer test my changes before merging. 
* [x] My changes are ready for merging.

### CODE REVIEW

**Comment by legoboyvdlp** [comment]
Not quite sure about this, I was thinking more of the Shuttle-style one where you can save scenarios as well. But this is good, as well, I'll check it and it probably can be expanded too?

**Comment by merspieler** [comment]
Shuttle-style is a bit of a different concept... I wanted and implemented a state safe across sessions as it would be like in reallife, you leave the plane and later it's in the same state as before.

**Comment by merspieler** [comment]
I've added a parameter. You can save and restore the state now with `save.save(filename)` and `save.restore(filename)` respectivly.

So it can be done independently from the automatic state save

**Comment by merspieler** [comment]
@merspieler todo: add a second parameter: array with props to save. provide `save.default` to start with.

**Comment by merspieler** [comment]
@legoboyvdlp please review and then merge. It's now fully flexible. You have to provide the list of props you want to save/restore and the file. `save.default` may be used as a starting point or you can just make your own list from scratch.

**Comment by legoboyvdlp** [comment]
Excellent, thank you!

**Pull request merged**
