### PR TITLE
Added backup nav

### PR DESCRIPTION
**Pull request by Kasluk24**
### Description of Changes

I added functionality to the backup nav.

#### Done so far:
- VORs
- LS
- ADFs
- Display changes MCDU RAD NAV page

#### Pending:
- BFO
- Display changes ~MCDU RAD NAV page and~ PFD when the backup nav is active

If you are happy with my additions so far, I'll do the pending changes.

### Checklist:

* [x] My changes follow the Contributing Guidelines. 
* [x] My changes implement realistic features. 
* [ ] Please have a main Developer test my changes before merging. 
* [x] My changes are ready for merging.

### CODE REVIEW

**Comment by legoboyvdlp** [comment]
Thanks. I will check this shortly :)

**Comment by legoboyvdlp** [comment]
@Kasluk24 Checking will be delayed, am investigating other issues with nav radios :)

**Comment by Kasluk24** [comment]
OK. Thanks for the info.

**Comment by legoboyvdlp** [comment]
@Kasluk24 thanks for these changes :)

Make sure your fork / branch is up to date with latest dev please :) 

I do not see any effect of the pushbuttons in the cockpit? RMP1 at least isn't working. I don't see any changes to the display or any lights illuminating. Maybe I am not using it correctly, but I pushed each button and it doesn't do anything. Especially the backup nav one.
See FCOM 34-30-30

image

image


If you could confirm these things are o.k., then happy to merge once you are.

**Comment by Kasluk24** [comment]
The MCDU RAD NAV page should now be displayed correctly when the standby nav is active. The changes at the PFD and the BFO are still pending, but I had to commit the changes because I'm working on two different computers.

I have no idea, why the standby nav doesn't work for you at all. It works for me perfectly. :thinking: Or did I misunderstand you?

fgfs-20200531195540

**Comment by legoboyvdlp** [comment]
Will pull again and check - thanks :)

**Comment by legoboyvdlp** [comment]
The lights on HF / AM are working now; unfortunately no lights working or any obvious effect on the nav pushbuttons.

I notice SEL light on RMP 2 goes by RMP 1, not RMP 2.

**Comment by Kasluk24** [comment]
Where on earth is the mistake! I have no idea. 
It's not possible to activate the standby nav with the NAV button on the RMP? This was possible before my changes and I have not changed anything, what could break that and for me, it still works. I also didn't any changes to the SEL lights.

**Comment by legoboyvdlp** [comment]
Yep, looks like the SEL light is existing regression - will fix that after this is merged :)

Yes, its quite strange; there is no nasal error either.

**Comment by mattmaring** [comment]
Nav isn't working for me either. Otherwise looks good when I set the properties manually in the browser.

ILS selections works correctly in standard modes, but stays the same in backup. I'll admit I'm not sure how it should work, but I can take a look at it after it's merged and I'm done with wind/second fuel system.

Thanks for working on the MCDU :)

**Comment by Kasluk24** [comment]
Now I have tested it with the Version 2020.1.2 on Windows (previously I've tested it on the 2020.2.0 Version on Linux) and it also works fine. The only problem I had, was holding the switch guard open and click on the button at the same time but with a bit practice, I did it :-). Does that work for you, or might the problem be there?

I'll look at the RMP XML again. Since there is no nasal error, a mistake might be there, but I don't think I'll find something new what could cause that strange behaviour.

Thanks for your help @legoboyvdlp and @mattmaring

**Comment by legoboyvdlp** [comment]
Ok - I think this might be why!

I am not seeing any yellow highlight for the pick animation, so I didn't notice the guard was clickable. Let's see what happens

**Comment by legoboyvdlp** [comment]
Yep - confirmed, this is why. Could you please see the overhead panel way of guarded switches?

What happens is:

- click guard to open once
- click switch, action occurs, guard closes
- OR click guard, guard closes

Hope this makes sense :)

Also, it is impossible to click on most of the guard -- only the edge. Maybe this is an issue in the 3D model?

Is there any way to tune ADF2, or is this inop when FMGCs fail?

**Comment by Kasluk24** [comment]
Ah, great. I'll change the switch guard as you described and will take a look at the Model.
ADF2 is tuned with the RMP2.

**Comment by mattmaring** [comment]
It works for me now, looks great :)

**Comment by legoboyvdlp** [comment]
O.k to merge? :) 

All works great!

**Comment by Kasluk24** [comment]
Yes, I think it makes sense to merge it now. BFO and the display changes at the PFD are not done yet, but I can do this in a second step. :-)

**Comment by legoboyvdlp** [comment]
Thanks!

**Comment by Kasluk24** [comment]
You're welcome and thanks also. It's a pleasure to contribute. :-)

**Pull request merged**
