### PR TITLE
Phase I - PFD improvements

### PR DESCRIPTION
**Pull request by mattmaring**
This is phase I of the PFD improvements. My FCOM source has disappeared, so it's gonna be awhile for phase II until I'm able to find a new FCOM source.

### Description of changes
- ILS warning flash
- Flashing QNH/STD when above/below transition alt/level
- Pulsing alt box, when about to reach selected alt
- V1, VR, V2 indications on PFD
- Flaps (F and S) speeds
- Max flap speeds
- Green dot speeds
- APPR page on MCDU (non-operative)
- Fix speeds view on TO page on MCDU

### Bugs fixed
- Fix ILS location
- ILS message stops flashing too early, change trigger property

### Checklist:
* [x] My changes follow the Contributing Guidelines. 
* [x] My changes implement realistic features. 
* [x] My changes are ready for merging.

### CODE REVIEW

**Comment by mattmaring** [comment]
We'll have to manually merge the mcdu.svg once the FMGC branch is done as I added some components in there as well. Should be simple.

**Comment by legoboyvdlp** [comment]
Ok, that's absolutely fine, thank you!

I can send you the FCOM - it is 132MB, so not over Github - will upload to dropbox.

**Comment by legoboyvdlp** [comment]
https://www.dropbox.com/s/qmxk11raes6jxve/Vol%201%20-%202012.pdf?dl=0

**Comment by legoboyvdlp** [comment]
What sources did you have for the various speeds now shown on the PFD? They don't show on the MCDU - only green dashes at the moment. I'd also like to check the flashing indicators - going to look on youtube for a source on that.

Otherwise, excellent as always ;)

**Comment by mattmaring** [comment]
Speeds aren't in the MCDU because the fuel calcs are not complete. I don't plan on putting the speeds into the MCDU until I can find the way the actual airbus calculates the values specifically for TO/APPR. Otherwise, the PFD is calculating them in real-time based on the weight. I believe most of the values are from PRO-SUP-10.

**Comment by merspieler** [comment]
What about geen dot speed? I've tried it with the default weight and got something just below 200kias in clean configuration which seem too low to me(I can be totaly wrong  tho)

The max flaps indication is still the wrong one.
ie. If the flaps lever is at 1, it should indicate the speed of flaps 2 (200kias). See DSC-31-40 P 8/32

Not sure what @legoboyvdlp has with the flashing indicators. They look fine to me.

**Comment by legoboyvdlp** [comment]
I already had the barberpole working showing the maximum speed with the **current** configuration - and the amber = appeared to be working fine for me @merspieler , what do you mean by > The max flaps indication is still the wrong one.
?

**Comment by legoboyvdlp** [comment]
@merspieler green dot follows the airbus formula as far as I see

**Comment by legoboyvdlp** [comment]
Possible bugs

1. the amber = symbol is showing at 217 knots while VFE next is 215 knots - are you using the speed at which the overspeed sounds (which is a few knots above VFE) rather than the actual VFE?

image


2. In my resource video: https://www.youtube.com/watch?v=n3TJMro_NzA

the F and S speeds do not show on the PFD till 400 feet AGL. This is not mentioned in the FCOM, however.


3. With flaps up, the managed speed is commanding only 200 knots, a bit above green dot - surely it should command 250 knots as normal?

4. I think I see what merspieler means:
image

It should be at 177 knots at that point.

5. Is the flashing amber thing inhibited when slats are out AND landing gear selected down OR landing gear locked down OR when the aircraft is established on the glideslope regardless?

**Comment by mattmaring** [comment]
For 1, I'm pretty sure it is at 215 on your picture :) Each tick mark is 10, not 5.

For 2, should be fixed now, if not, let me know!

I believe 3 was a bug already on the pfd. I noticed many issues with the managed speed, but have not had a chance to go through and thoroughly test that. All I have done to it is set it equal to V2 during takeoff.

For 4, I see what you mean. Should be fixed now, if not, let me know!

For 5, I have not made it inhibited in those scenarios. You are talking about the alt flash, correct?

**Comment by merspieler** [comment]
looks good to me, a GO for merge

**Review by merspieler — APPROVED** [review]

**Comment by legoboyvdlp** [comment]
See above though first. Once they are dealt with I will be glad to merge :)

**Comment by legoboyvdlp** [comment]
> For 1, I'm pretty sure it is at 215 on your picture :) Each tick mark is 10, not 5.

Oops - sorry!

> For 2, should be fixed now, if not, let me know!
> For 4, I see what you mean. Should be fixed now, if not, let me know!

Thank you. :)

> I believe 3 was a bug already on the pfd. I noticed many issues with the managed speed, but have not had a chance to go through and thoroughly test that. All I have done to it is set it equal to V2 during takeoff.

Ok.


> For 5, I have not made it inhibited in those scenarios. You are talking about the alt flash, correct?
Yes, the entire altitude alert system including c-chord and that. When I add the c-chord then I will also add these.

**Comment by merspieler** [comment]
There's a minor detail that sliped my attention previously... it's, again, about the speed indication of the next flaps setting: When in flaps 1, it's currently showing the speed of flaps 1+F but it should show the speed for flaps 2 as 1+F is not manually selectable.

**Pull request merged**
