### PR TITLE
Update README.md to be more clear on how to connect to the Remote MCDU

### PR DESCRIPTION
**Pull request by NewoIsTaken**
### Description of Changes:
Please read the changed information in the commit.

### Checklist:
* [x] My changes follow the Contributing Guidelines. 
* [ ] Please have a main Developer test my changes before merging.

### CODE REVIEW

**Comment by merspieler** [comment]
The brackets for must replace are `<>` while `[]` usually stands for optional parameter...
Please change it it according to that.

**Comment by NewoIsTaken** [comment]
@merspieler, thanks for the information! I have updated accordingly!

**Comment by merspieler** [comment]
localhost is the very same as 127.0.0.1 so no need at all to name both

**Comment by NewoIsTaken** [comment]
@merspieler I was just trying to point out that you can do either a hostname like "localhost" and IP like "127.0.0.1."

**Comment by merspieler** [comment]
hm... sounds too much for me but maybe for ppl with less technical understanding, you have a point...
In that case `IP/Hostname; e.g. localhost/127.0.0.1` should be changed to `IP/Hostname; e.g. 127.0.0.1/localhost` to maintain the order.

**Comment by NewoIsTaken** [comment]
@merspieler I have done that now!

**Pull request merged**
